### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by balexandre** [TycheOrg/Home#3]
from NuGet output

> Could not install package 'Tyche 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by M-Zuber** [comment]
Thank you for reporting it. I will try and look into it this evening. Bug me here or in the gitter room if I take too long to respond

**Comment by M-Zuber** [comment]
Issue moved to [TycheOrg/Tyche #4](https://github.com/TycheOrg/Tyche/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
